---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: ui-h5-game-city-xxl
  labels:
    app: ui-h5-game-city-xxl
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: ui-h5-game-city-xxl
      labels:
        app: ui-h5-game-city-xxl
    spec:
      nodeSelector:
        service: "service"
      containers:
        - name: ui-h5-game-city-xxl
          image: registry-vpc.cn-shenzhen.aliyuncs.com/jlyx/xxl-master:4244_201912241516
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: ui-h5-game-city-xxl

---
apiVersion: v1
kind: Service
metadata:
  name: ui-h5-game-city-xxl
  namespace: service
spec:
  selector:
    app: ui-h5-game-city-xxl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ui-h5-game-city-xxl-ingress-route
  namespace: service
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cityxxl.game.h5.juliyouxiang.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: ui-h5-game-city-xxl
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ui-h5-game-city-xxl-ingress-route
  namespace: service
spec:
  compress: {}