---
# Source: skywalking/templates/oap-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: skywalking-skywalking-oap
  labels:
    app: skywalking
    chart: skywalking-1.0.0
    component: "skywalking-oap"
    heritage: Helm
    release: skywalking
  namespace: skywalking
spec:
  type: ClusterIP
  ports:
  - port: 12800
    name: rest
  - port: 11800
    name: grpc
  selector:
    app: skywalking
    component: "skywalking-oap"
    release: skywalking
