---
# Source: skywalking/templates/oap-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skywalking
  labels:
    app: skywalking
    chart: "skywalking-1.0.0"
    release: "skywalking"
    heritage: "Helm"
  namespace: skywalking
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skywalking
subjects:
  - kind: ServiceAccount
    name: skywalking-skywalking-oap
    namespace: skywalking
