---
# Source: skywalking/templates/oap-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: skywalking
    chart: skywalking-1.0.0
    component: "skywalking-oap"
    heritage: Helm
    release: skywalking
  name: skywalking-skywalking-oap
  namespace: skywalking