---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: logging
  name: nfs-pv-logging
  labels:
    app: nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=3
    - nolock,tcp,noresvport
  nfs:
    path: /product/logging
    server: 217734b352-gsl17.cn-shenzhen.nas.aliyuncs.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: logging
  name: nfs-pvc-logging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: nfs