---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: ui-admin
  labels:
    app: ui-admin
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: ui-admin
      labels:
        app: ui-admin
    spec:
      nodeSelector:
        service: "service"
      containers:
        - name: ui-admin
          image: registry-vpc.cn-shenzhen.aliyuncs.com/jlyx/admin-master:3381_201912061617
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - name: wechat-auth
              mountPath: /usr/share/nginx/html/MP_verify_5jVtWA0wKrgzOUZ3.txt
              readOnly: true
              subPath: MP_verify_5jVtWA0wKrgzOUZ3.txt
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: wechat-auth
          configMap:
            name: wechat-auth
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: ui-admin

---
apiVersion: v1
kind: Service
metadata:
  name: ui-admin
  namespace: service
spec:
  selector:
    app: ui-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ui-admin-ingress-route
  namespace: service
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`admin.juliyouxiang.com`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: ui-admin
          port: 80
  tls:
    secretName: admin-https-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ui-admin-ingress-route
  namespace: service
spec:
  compress: {}