apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    image: redis:5.0-alpine
    imagePullPolicy: IfNotPresent
    command:
      - "redis-server"
      - "/redis/sentinel.conf"
      - "--sentinel"
      - "--protected-mode"
      - "no"
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    customConfig:
      - "down-after-milliseconds 2000"
      - "failover-timeout 3000"
    exporter:
      enabled: true
      image: leominov/redis_sentinel_exporter:1.3.0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: middleware
                  operator: In
                  values:
                    - middleware

  redis:
    securityContext:
      runAsNonRoot: False
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    replicas: 3
    image: pmem/redis
    imagePullPolicy: IfNotPresent
    command:
      - "redis-server"
      - "/redis/redis.conf"
      - "--pmdir"
      - "/data"
      - "100Mb"
      - "--protected-mode"
      - "no"
    shutdownConfigMap: "shutdown-configmap"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    customConfig:
      - "maxclients 100"
      - "hz 50"
      - "timeout 60"
      - "tcp-keepalive 60"
      - "client-output-buffer-limit normal 0 0 0"
      - "client-output-buffer-limit slave 1000000000 1000000000 0"
      - "client-output-buffer-limit pubsub 33554432 8388608 60"
    exporter:
      enabled: true
      image: oliver006/redis_exporter:v0.33.0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: middleware
                  operator: In
                  values:
                    - middleware
    storage:
      persistentVolumeClaim:
        metadata:
          name: redisfailover-pmem-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
          storageClassName: alicloud-nas