---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik-logging
  labels:
    app: traefik-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-logging
  template:
    metadata:
      labels:
        app: traefik-logging
    spec:
      nodeSelector:
        gateway-temp: "gateway-temp"
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik-logging
          image: traefik:v2.0
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --entrypoints.tcp.Address=:6666
            - --providers.kubernetescrd
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.email=foo@you.com
            - --certificatesresolvers.default.acme.storage=acme.json
            - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
            - name: tcp
              containerPort: 6666
              hostPort: 6666