---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: service
  name: sc-wechat-goods
  labels:
    app: sc-wechat-goods
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: sc-wechat-goods
      labels:
        app: sc-wechat-goods
    spec:
      nodeSelector:
        service: "service"
      containers:
        - name: sc-wechat-goods
          image: registry-vpc.cn-shenzhen.aliyuncs.com/jlyx/sc-wechat-goods-master:3258_201912041430
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 45
          env:
            - name: CLOUD_EUREKA_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: business-service-config
                  key: CLOUD_EUREKA_DEFAULTZONE
            - name: JASYPT_ENCRYPTOR_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: business-service-config
                  key: JASYPT_ENCRYPTOR_PASSWORD
          envFrom:
            - configMapRef:
                name: business-service-config
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - name: app-logs
              mountPath: /logs
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.0.0
          volumeMounts:
            - name: app-logs
              mountPath: /logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: app-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: sc-wechat-goods