---
# Source: skywalking/charts/elasticsearch/templates/master-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: elasticsearch
    chart: elasticsearch-1.32.0
    component: "master"
    heritage: Helm
    release: skywalking
  name: skywalking-elasticsearch-master
  namespace: skywalking